services:
  accounts:
    image: viveksingh1693/accounts:s4
    container_name: accounts-ms
    ports:
      - "8080:8080"
    environment:
      - "spring.profiles.active=local"
    networks:
      - microservices-network
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  cards:
    image: viveksingh1693/cards:s4
    container_name: cards-ms
    ports:
      - "9000:9000"
    environment:
      - "spring.profiles.active=local"
    networks:
      - microservices-network
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  loans:
    image: viveksingh1693/loans:s4
    container_name: loans-ms
    ports:
      - "8090:8090"
    environment:
      - "spring.profiles.active=local"
    networks:
      - microservices-network
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
networks:
  microservices-network:
    driver: bridge
  # zuul-api-gateway:
  #   image: viveksingh1693/zuul-api-gateway:s4
  #   ports:
  #     - "8765:8765"
  #   depends_on:
  #     - accounts
  #     - cards
  #     - loans
  #   networks:
  #     - microservices-network

  # config-server:
    # image: viveksingh1693/config-server:s4
    # ports:
    #   - "8888:8888"
    # environment:
    #   - "spring.profiles.active=local"
    # networks:
    #   - microservices-network