spring.application.name=message
server.port=9010

spring.cloud.function.definition=email|sms

spring.cloud.stream.bindings.emailsms-in-0.destination=send-communication
spring.cloud.stream.bindings.emailsms-in-0.group=${spring.application.name}
spring.cloud.stream.bindings.emailsms-out-0.destination=communication-send


spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.port=${RABBITMQ_PORT}
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}
spring.rabbitmq.connection-timeout=30000



spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
# spring.mail.properties.mail.smtp.starttls.required=true